POST http://localhost:5501/transfer
Content-Type:  application/json

{
  "shema": {
    "cardFromNumber": "1111111111111112",
    "cardFromValidTill": "1224",
    "cardFromCVV": "111",
    "cardToNumber": "2222222222222221"
  },
  "amount": {
    "value": "5000",
    "currency": "aaaaa"
  }
}
###########################
POST http://localhost:5501/transfer
Content-Type:  application/json

{
"a":"1"
}


########################

GET http://localhost:5501/test

